apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-producer
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - $KAFKA_HOME/bin/kafka-console-producer.sh --broker-list 172.17.0.2:9092
          --topic test
        image: spotify/kafka
        name: kafka_producer
        resources: {}
      restartPolicy: Always
status: {}
