apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - env:
        - name: ADVERTISED_HOST
          value: localhost
        - name: ADVERTISED_PORT
          value: "9092"
        image: spotify/kafka
        name: kafka
        ports:
        - containerPort: 2181
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
